version: "3.7"

services:
  gameapp-redis:
    image: redis:6.2.14
    container_name: gameapp-redis
    restart: always 
    ports: 
      - '6380:6379'
    command: redis-server --loglevel warning --protected-mode no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - gameapp-redis-data:/data
  
  gameapp-database:
    image: mysql:8.0
    container_name: gameapp-database
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt0lk2o20

volumes:
  dbdata:
  gameapp-redis-data:
